---
title: "ABCD Gender Identity"
author: "John Jardine"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cosmo
    toc: TRUE
---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

# Code

## Packages

```{r packages, echo = TRUE, message = FALSE}
if(!("pacman" %in% rownames(installed.packages()))) {install.packages("pacman")}
pacman::p_load(dplyr, purrr, tidyr, haven, survey, ggplot2, gridExtra, knitr, kableExtra)

options(knitr.kable.NA = "")

# function to relabel variables so the order of the new levels is the same as how it is specified in the case_when statement
fct_case_when = function(...) {
  args <- as.list(match.call())
  levels <- sapply(args[-1], function(f) f[[3]])
  levels <- levels[!is.na(levels)]
  factor(dplyr::case_when(...), levels=levels)
}
```

## Mplus Data Prep

```{r mplus_data_prep, echo = TRUE, message = FALSE, results = "asis"}
# local path where the master ABCD dataset is located
path = "C:/Users/jjardine/Desktop/ABCD/data/master/"

# load in the master ABCD dataset
load(paste0(path, "abcd_master.RDa"))

# create a copy of the dataset to use for the LCA
mplus_gender_lca = abcd_master

# create dummy variables for the different responses to "are you transgender?"
for(i in c(0, 12, 24, 36)) {
  mplus_gender_lca = mplus_gender_lca %>%
    mutate(!!sym(paste0("trans_no_", i))    := case_when(!!sym(paste0("kbi_y_trans_id_", i)) == 3 ~ 1,
                                                         !!sym(paste0("kbi_y_trans_id_", i)) %in% c(1, 2, 4) ~ 0),
           
           !!sym(paste0("trans_maybe_", i)) := case_when(!!sym(paste0("kbi_y_trans_id_", i)) == 2 ~ 1,
                                                         !!sym(paste0("kbi_y_trans_id_", i)) %in% c(1, 3, 4) ~ 0),
           
           !!sym(paste0("trans_yes_", i))   := case_when(!!sym(paste0("kbi_y_trans_id_", i)) == 1 ~ 1,
                                                         !!sym(paste0("kbi_y_trans_id_", i)) %in% c(2, 3, 4) ~ 0),
           
           !!sym(paste0("trans_und_", i))   := case_when(!!sym(paste0("kbi_y_trans_id_", i)) == 4 ~ 1,
                                                         !!sym(paste0("kbi_y_trans_id_", i)) %in% c(1, 2, 3) ~ 0))
}
rm(i)

mplus_gender_lca = mplus_gender_lca %>%
  # get just the variables of interest 
  select(src_subject_id, matches("trans_no"), matches("trans_maybe"), matches("trans_yes"), matches("trans_und"),
         matches("felt_gender_same_y"), matches("felt_gender_opp_"), matches("wish_gender_opp_y"), matches("gender_express_opp_y")) %>%
  select(-matches("48"))

# remove cases where every variable except the ID is missing
mplus_gender_lca = mplus_gender_lca[!(rowSums(is.na(mplus_gender_lca)) == ncol(mplus_gender_lca) - 1), ]

# create a simpler id variable
mplus_gender_lca = mplus_gender_lca %>%
  mutate(id = row_number()) %>%
  relocate(id)

# set missing values to 999
mplus_gender_lca = mplus_gender_lca %>% mutate(across(everything(), ~ ifelse(is.na(.x), 999, .x)))

# save the file locally
path = "C:/Users/jjardine/Desktop/ABCD/data/"
write.table(mplus_gender_lca %>% select(-src_subject_id), paste0(path, "gender_and_sex/mplus_gender_lca.csv"), sep = ",", row.names = FALSE, col.names = FALSE)
```

## GEE Data Prep

```{r demo_prep, echo = TRUE, message = FALSE}
# read in the 4-class LCA solution
res4 = read.delim(paste0(path, "gender_and_sex/mplus_gender_lca_c4.txt"), sep = "", header = FALSE)

# add the class variables from the results to the original mplus dataset
mplus_gender_lca$class_id_4 = res4[, ncol(res4)]

# create a new dataset adding the class ID to the master dataset (2 respondents who weren't included in the LCA are dropped)
dat = inner_join(abcd_master, mplus_gender_lca %>% distinct(src_subject_id, class_id_4), by = "src_subject_id")

# select just the variables of interest
dat = dat %>%
  select(src_subject_id, class_id_4, matches("longDummy"), matches("site_id_l"), matches("rel_family_id"), interview_age_0, sex_at_birth_0, race_ethnicity_0,
         demo_prnt_marital_v2_0, demo_prnt_prtnr_ed_agg_0, demo_prnt_prtnr_empl_0, demo_comb_income_agg_0, matches("bool_b"), matches("any_curious"), matches("try_soon"))

# reshape the data into long format
dat = dat %>%
  pivot_longer(cols = -c(src_subject_id, class_id_4),
               names_to = c(".value", "event"),
               names_pattern = "(.*)_(.*)") %>%
  mutate(event = as.numeric(event))

# for all covariates except the class ID, propagate the value at baseline through to all events
dat = dat %>%
  group_by(src_subject_id) %>%
  mutate(across(c(rel_family_id, interview_age, sex_at_birth, race_ethnicity, demo_prnt_marital_v2, demo_prnt_prtnr_ed_agg, demo_prnt_prtnr_empl, demo_comb_income_agg), ~ .x[event == 0])) %>%
  ungroup()

# dichotomize the age variables as 0 = 9 or younger, 1 = 10 or older
dat = dat %>%
  mutate(interview_age = case_when(interview_age < 10 ~ 0,
                                   interview_age >= 10 ~ 1))

# filter the data to just the full-year events (with the qualifier the respondent was actually present at the given event)
dat = dat %>% filter(event %in% c(0, 12, 24, 36, 48) & longDummy == 1) %>% select(-longDummy)

# convert the event variable to the year number
dat = dat %>% mutate(event = event / 12)

# convert the site IDs to integers
dat = dat %>% mutate(site_id_l = as.numeric(gsub("\\D", "", site_id_l)))

# save the file locally, and convert the subject IDs to integers
path = "C:/Users/jjardine/Desktop/ABCD/data/gender_and_sex/"
write_dta(dat %>% group_by(src_subject_id) %>% mutate(src_subject_id = cur_group_id()) %>% ungroup(), paste0(path, "abcd_gender_sub.dta"))
```

# Tables

## Table 1

```{r table_1, echo = FALSE, message = FALSE, results = "asis"}
# recode the covariates for displaying in table 1
temp = dat %>%
  mutate(
    
    interview_age = fct_case_when(interview_age == 0 ~ "9 or younger",
                                  interview_age == 1 ~ "10 or older"),
    
    sex_at_birth = fct_case_when(sex_at_birth == 0 ~ "Male",
                                 sex_at_birth == 1 ~ "Female"),
    
    race_ethnicity = fct_case_when(race_ethnicity == 1 ~ "Non-Hispanic White only",
                                   race_ethnicity == 2 ~ "Non-Hispanic Black only",
                                   race_ethnicity == 3 ~ "Hispanic",
                                   race_ethnicity == 4 ~ "Non-Hispanic Asian only",
                                   race_ethnicity == 5 ~ "Non-Hispanic other race or multiracial"),
    
    demo_prnt_prtnr_ed_agg   = fct_case_when(demo_prnt_prtnr_ed_agg == 0 ~ "Less than high school",
                                             demo_prnt_prtnr_ed_agg == 1 ~ "High school",
                                             demo_prnt_prtnr_ed_agg == 2 ~ "Some college",
                                             demo_prnt_prtnr_ed_agg == 3 ~ "Associate's degree",
                                             demo_prnt_prtnr_ed_agg == 4 ~ "Bachelor's degree or higher"),
    
    demo_prnt_marital_v2 = fct_case_when(demo_prnt_marital_v2 == 0 ~ "Not married",
                                         demo_prnt_marital_v2 == 1 ~ "Married"),
    
    demo_prnt_prtnr_empl = fct_case_when(demo_prnt_prtnr_empl == 0 ~ "Neither parent or partner works full-time",
                                         demo_prnt_prtnr_empl == 1 ~ "At least one of parent or partner works full-time"),
    
    demo_comb_income_agg   = fct_case_when(demo_comb_income_agg == 0 ~ "$24,999 or lower",
                                           demo_comb_income_agg == 1 ~ "$25,000 to 49,999",
                                           demo_comb_income_agg == 2 ~ "$50,000 to 74,999",
                                           demo_comb_income_agg == 3 ~ "$75,000 to 99,999",
                                           demo_comb_income_agg == 4 ~ "$100,000 or greater",
                                           demo_comb_income_agg == 5 ~ "Don't know",
                                           demo_comb_income_agg == 6 ~ "Refuse to answer"),
    
    class_id_4   = fct_case_when(class_id_4 == 4 ~ "'Cisgender'",
                                 class_id_4 == 2 ~ "'Naive'",
                                 class_id_4 == 3 ~ "'Questioning'",
                                 class_id_4 == 1 ~ "'Transgender'"))

# function to return the unweighted sample sizes and percentages for a given variable
uw_sizes_percent = function(.x) {
  
  # get the unweighted sample sizes
  uw_sizes = temp %>% filter(event == 0) %>% count(!!sym(.x))
  
  # get the unweighted percents
  uw_percent = temp %>%
    filter(event == 0) %>%
    count(!!sym(.x)) %>%
    mutate(p = ifelse(is.na(!!sym(.x)), sprintf("%.2f", n / sum(n) * 100),
                      sprintf("%.2f", n / sum(n[!is.na(!!sym(.x))]) * 100))) %>%
    select(-n)
  
  # join the sample sizes and percents together
  mat = inner_join(uw_sizes, uw_percent, by = .x) %>%
    rename(value = !!sym(.x)) %>%
    select(value, n, p)
  
  # extract the missing sample size and percent
  miss = mat %>%
    filter(is.na(value)) %>%
    summarize(miss = paste0(prettyNum(n, ","), " (", p, "%)")) %>%
    mutate(miss = ifelse(miss == " (%)", "0 (0%)", miss))
  
  # return the sample sizes and percents
  bind_cols(miss,
            mat %>% filter(!is.na(value))) %>%
    mutate(n_p = paste0(prettyNum(n, ","), " (", p, "%)"),
           value = as.character(value)) %>%
    select(value, n_p, miss) %>%
    mutate(miss = ifelse(row_number() == 1, miss, NA),
           variable = .x) %>%
    relocate(variable)
}

map(c("interview_age", "sex_at_birth", "race_ethnicity", "demo_prnt_prtnr_ed_agg", "demo_prnt_marital_v2", "demo_prnt_prtnr_empl", "demo_comb_income_agg", "class_id_4"),
    uw_sizes_percent) %>%
  bind_rows() %>%
  mutate(variable = case_match(variable,
                               "interview_age" ~ "Child's age at baseline",
                               "sex_at_birth" ~ "Child's sex at birth",
                               "race_ethnicity" ~ "Child's race / ethnicity",
                               "demo_prnt_prtnr_ed_agg" ~ "Highest level of parental education",
                               "demo_prnt_marital_v2" ~ "Parental marital status",
                               "demo_prnt_prtnr_empl" ~ "Parental employment status",
                               "demo_comb_income_agg" ~ "Total combined family income",
                               "class_id_4" ~ "Latent class")) %>%
  group_by(variable) %>%
  mutate(variable = ifelse(row_number() == 1, variable, NA)) %>%
  kable(format = "html",
        caption = paste0("Table 1: Sample Characteristics of Respondents in the ABCD Study (n = ", prettyNum(dat %>% distinct(src_subject_id) %>% nrow(), big.mark = ","), ")"),
        col.names = c("", "", "n (%)", "missing"),
        digits = 2) %>%
  kable_classic_2("striped") %>%
  column_spec(1, bold = TRUE) %>%
  column_spec(1:3, border_right = TRUE) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(c(2, 4, 9, 14, 16, 18, 25), extra_css = "border-bottom: 1px solid") %>%
  footnote(general = "All measures except the latent class were assessed at baseline. The latent classes were fitted using data from baseline through the year 3 follow-up. Two respondents with missing data for all of the gender-related questions were not included in the analysis.",
           general_title = "")

cat("<br><br><br><br><br>")
```

## Table 2

```{r table_2, echo = FALSE, message = FALSE, results = "asis"}
pct = map(c("interview_age", "sex_at_birth", "race_ethnicity", "demo_prnt_prtnr_ed_agg", "demo_prnt_marital_v2", "demo_prnt_prtnr_empl", "demo_comb_income_agg"),
          function(.x) {
            dat %>%
              filter(event == 0) %>%
              count(class_id_4, !!sym(.x)) %>%
              filter(!is.na(!!sym(.x))) %>%
              group_by(class_id_4) %>%
              mutate(pct = paste0(n, " (", sprintf("%.2f", n / sum(n) * 100), ")"),
                     var = .x) %>%
              rename(val = !!sym(.x)) %>%
              pivot_wider(names_from = class_id_4, values_from = pct, id_cols = c(var, val)) }) %>%
  bind_rows() %>%
  rename(pct_1 = `1`,
         pct_2 = `2`,
         pct_3 = `3`,
         pct_4 = `4`)

mat = read.csv(paste0(path, "class_id_4.csv"))

sSize = as.numeric(gsub("=", "", mat[nrow(mat) - 1, 2]))

mat = mat[-c(1:2, nrow(mat) - 1, nrow(mat)), ] %>% `rownames<-`(NULL)

mat = mat[-seq(1, nrow(mat), nrow(mat) / 4), ] %>% `rownames<-`(NULL)

mat = mat %>%
  `colnames<-`(c("var", "val")) %>%
  mutate(class_id_4 = rep(1:4, each = nrow(mat) / 4),
         var = ifelse(lag(var) != "=" & row_number() != 1, lag(var), var),
         val = gsub(",", ", ", val),
         type = ifelse(grepl(",", val), "ci", "pe"),
         across(everything(), ~ gsub("=", "", .x))) %>%
  pivot_wider(names_from = type, values_from = val) %>%
  mutate(pe = paste0(pe, " (", ci, ")"),
         ci = NULL) %>%
  pivot_wider(names_from = class_id_4, values_from = pe) %>%
  mutate(val = as.numeric(gsub("\\..*", "", var)),
         var = gsub(".*\\.", "", var))

covariates = c("interview_age", "sex_at_birth", "race_ethnicity", "demo_prnt_prtnr_ed_agg", "demo_prnt_marital_v2", "demo_prnt_prtnr_empl", "demo_comb_income_agg")
covariates = data.frame(myVar = rep(covariates, unlist(map(covariates, function(.x) { length(levels(temp %>% pull(.x))) }))),
                        myVal = unlist(map(covariates, function(.x) { sort(unique(dat %>% pull(.x))) })),
                        myLabel = unlist(map(covariates, function(.x) { levels(temp %>% pull(.x)) })))

full_join(pct, mat, by = c("var", "val")) %>%
  select(var, val, pct_4, pct_2, `2`, pct_3, `3`, pct_1, `1`) %>%
  mutate(val = covariates %>% filter(myVar == var & myVal == val) %>% pull(myLabel),
         var = case_when(val == "9 or younger" ~ "Child's age at baseline",
                         val == "Male" ~ "Child's sex at birth",
                         val == "Non-Hispanic White only" ~ "Child's race / ethnicity",
                         val == "Less than high school" ~ "Highest level of parental education",
                         val == "Not married" ~ "Parental marital status",
                         val == "Neither parent or partner works full-time" ~ "Parental employment status",
                         val == "$24,999 or lower" ~ "Total combined family income"),
         across(c(`2`, `3`, `1`), ~ ifelse(is.na(.x), "Ref.", .x))) %>%
  kable(format = "html",
        align = "llrrrrrrr",
        caption = paste0("Table 2: Demographic Predictors of Latent Class Membership - Prevalence and Risk Ratios (n =", prettyNum(sSize, big.mark = ","), ")"),
        col.names = c("", "", "n (%)", "n (%)", "RR (95% CI)", "n (%)", "RR (95% CI)", "n (%)", "RR (95% CI)")) %>%
  kable_classic_2("striped") %>%
  column_spec(1, bold = TRUE) %>%
  column_spec(c(2, 3, 5, 7), border_right = TRUE) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(c(2, 4, 9, 14, 16, 18), extra_css = "border-bottom: 1px solid") %>%
  add_header_above(c("", "", "'Cisgender'", "'Naive'" = 2, "'Questioning'" = 2, "'Transgender'" = 2), bold = TRUE) %>%
  add_header_above(c("", "", "Latent Class" = 7), bold = TRUE) %>%
  footnote(general = "The 'cisgender' class was treated as the base class. All covariates were measured at baseline. The latent classes were fitted using data from baseline through the year 3 follow-up.",
           general_title = "")

cat("<br><br><br><br><br>")
```

## Table 3

```{r table_3, echo = FALSE, warning = FALSE, message = FALSE, results = "asis"}
temp = dat %>%
  group_by(src_subject_id) %>%
  summarize(class_id_4 = unique(class_id_4),
            across(c(alc_any_curious, tob_any_curious, mj_any_curious, alc_try_soon, tob_try_soon, mj_try_soon, drink_bool_b, tob_bool_b, mj_bool_b),
                   ~ ifelse((NA %in% unique(.x)) & (length(unique(.x)) == 1), NA, max(.x, na.rm = TRUE)))) %>%
  ungroup()

map(names(temp)[-c(1, 2)],
    function(.x) {
      myDes = svydesign(ids = ~src_subject_id, data = temp %>% rename(myOutcome = !!sym(.x)))
      res = svyciprop(~myOutcome, myDes, method = "logit")
      
      overallSamp = data.frame(pct_ci = paste0(sprintf("%.2f", as.numeric(res) * 100), " (", sprintf("%.2f", attr(res, "ci")[1] * 100), ", ", sprintf("%.2f", attr(res, "ci")[2] * 100), ")"),
                               class_id_4 = "Overall Sample") %>%
        rename(!!sym(.x) := pct_ci)
      
      res = svyby(~myOutcome, ~class_id_4, myDes, svyciprop, vartype = "ci", method = "logit") %>%
        mutate(pct_ci = paste0(sprintf("%.2f", myOutcome * 100), " (", sprintf("%.2f", ci_l * 100), ", ", sprintf("%.2f", ci_u * 100), ")"),
               class_id_4 = case_match(class_id_4,
                                       1 ~ "Transgender",
                                       2 ~ "Naive",
                                       3 ~ "Questioning",
                                       4 ~ "Cisgender")) %>%
        rename(!!sym(.x) := pct_ci) %>%
        select(-c(myOutcome, ci_l, ci_u))
      
      bind_rows(overallSamp, res)
    }) %>%
  reduce(inner_join, by = "class_id_4") %>%
  bind_rows(temp %>%
              summarize(across(c(alc_any_curious, tob_any_curious, mj_any_curious, alc_try_soon, tob_try_soon, mj_try_soon, drink_bool_b, tob_bool_b, mj_bool_b), ~ paste0("n = ", prettyNum(sum(!is.na(.x)), ",")))) %>%
              mutate(class_id_4 = "")) %>%
  relocate(class_id_4) %>%
  arrange(match(class_id_4, c("", "Overall Sample", "Cisgender", "Naive", "Questioning", "Transgender"))) %>%
  kable(format = "html",
        align = "lrrrrrrrrr",
        caption = "Table 3: Prevalence of Curiosity to Use, Intention to Use, and Use of Alcohol, Nicotine/Tobacco, and Cannabis Among Respondents in the ABCD Study: % (95% CI)",
        col.names = c("", rep(c("Alcohol", "Nicotine/Tobacco", "Cannabis"), 3))) %>%
  kable_classic_2("striped") %>%
  column_spec(1, border_right = TRUE) %>%
  column_spec(c(4, 7), border_right = TRUE) %>%
  row_spec(0:1, bold = TRUE) %>%
  add_header_above(c("", "Curiosity to Use" = 3, "Intention to Use" = 3, "Use" = 3), bold = TRUE)

cat("<br><br><br><br><br>")
```

## Table 4

```{r table_4, echo = FALSE, message = FALSE, results = "asis"}
map(c("drink_bool_b", "tob_bool_b", "mj_bool_b", "alc_any_curious", "tob_any_curious", "mj_any_curious", "alc_try_soon", "tob_try_soon", "mj_try_soon"),
    function (.x) {
      mat = read.csv(paste0(path, .x, ".csv")) %>%
        `colnames<-`(c("var", "val")) %>%
        mutate(var = ifelse(lag(var) != "=", lag(var), var),
               val = gsub(",", ", ", val),
               type = ifelse(grepl(",", val), "ci", "pe"),
               across(everything(), ~ gsub("=", "", .x)))
      
      sSize = paste0("n = ", prettyNum(mat[nrow(mat) - 1, 2], big.mark = ","), "")
      
      mat %>%
        filter(grepl("class", var)) %>%
        pivot_wider(names_from = type, values_from = val) %>%
        mutate(pe = paste0(pe, " (", ci, ")"),
               ci = NULL) %>%
        add_row(var = NA, pe = sSize, .before = 1) %>%
        add_row(var = "4.class_id_4", pe = "Ref.", .before = 2) %>% `colnames<-`(c("var", paste0("pe_", sub("_[^_]*$", "", .x)))) %>%
        arrange(!is.na(var), match(var, c("4.class_id_4", "2.class_id_4", "3.class_id_4", "1.class_id_4")))
    }) %>%
  reduce(inner_join, by = "var") %>%
  mutate(var = case_match(var,
                          "4.class_id_4" ~ "'Cisgender'",
                          "2.class_id_4" ~ "'Naive'",
                          "3.class_id_4" ~ "'Questioning'",
                          "1.class_id_4" ~ "'Transgender'")) %>%
  kable(format = "html",
        align = "lrrrrrrrrr",
        caption = "Table 4: Adjusted Odds Ratios for Substance Use and Intentions to Use as Functions of the Latent Class: aOR (95% CI)",
        col.names = c("", rep(c("Alcohol", "Tobacco", "Marijuana"), 3))) %>%
  kable_classic_2("striped") %>%
  column_spec(1, bold = TRUE, border_right = TRUE) %>%
  column_spec(c(4, 7), border_right = TRUE) %>%
  row_spec(c(0, 1), bold = TRUE) %>%
  add_header_above(c("", "Use" = 3, "Curiosity" = 3, "'Will Try Soon'" = 3), bold = TRUE) %>%
  footnote(general = "All models are adjusted for time, the respondent's age at baseline, the respondent's sex, the respondent's race/ethnicity, parental marital status, parental education level, parental employment status, and total combined family income. All outcomes are time-varying; all covariates (except time) are time-invariant.\n\nFor alcohol, ‘use’ is defined as having tried a full drink of beer, wine, or liquor. For tobacco, ‘use’ is defined as having tried a tobacco cigarette; an electronic cigarette, vape pen, or e-hookah; smokeless tobacco, chew, or snus; cigars, including traditional cigars, little cigars, or cigarillos; hookah; pipes; and nicotine replacements, such as patches, gums, nasal sprays, inhalers, and lozenges. A puff of a tobacco product counts as ‘use’. For marijuana, ‘use’ is defined as having tried smoking marijuana; blunts; marijuana that you eat, such as pot cookies, gummy bears, or brownies; marijuana oils or concentrates; marijuana infused alcohol drinks; concentrated marijuana tinctures; vaping marijuana flower or bud; and vaping marijuana oils or concentrates. More detailed examples of certain methods are given in the ABCD codebooks. A puff of a marijuana product counts as ‘use’.\n\nThe curiosity measure was dichotomized as 0 = ‘not at all curious’, 1 = ‘a little curious’ to ‘very curious’. The ‘will try soon’ measure was dichotomized as 0 = ‘probably not’ to ‘definitely not’, 1 = ‘probably yes’ to ‘definitely yes’. For a given event, only respondents who knew what the substance was, but hadn’t tried it yet (including just a sip of alcohol or a puff of tobacco / marijuana), were asked about their curiosity and intention to use that substance.
",
general_title = "")

cat("<br><br><br><br><br>")
```

# Plots

```{r plots, echo = FALSE, message = FALSE, results = "asis", fig.width = 8, fig.height = 8}
# common plotting theme to use
theme_set(
  theme_bw() +
    theme(strip.text.x = element_text(size = 14, color = "black"),
          strip.text.y = element_text(size = 14, color = "black"),
          strip.background = element_rect(fill = "#DDDDDD"),
          axis.text.x = element_text(size = 14, color = "black"),
          axis.text.y = element_text(size = 14, color = "black"),
          legend.title = element_text(size = 14, color = "black"),
          legend.text = element_text(size = 14, margin = margin(l = 5, r = 15), color = "black"),
          legend.position = "bottom",
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 14, margin = margin(t = 0, r = 10, b = 0, l = 0), color = "black"),
          plot.title = element_blank(),
          axis.ticks.length = unit(0.25, "cm"),
          panel.grid.minor.x = element_blank())
)

# for the mplus lca dataset, set missing values to NA
mplus_gender_lca = mplus_gender_lca %>% mutate(across(everything(), ~ ifelse(.x == 999, NA, .x)))

# reshape the dataset back to long format
mplus_gender_lca = mplus_gender_lca %>%
  pivot_longer(cols = -c(id, src_subject_id, class_id_4),
               names_to = c(".value", "event"),
               names_pattern = "(.*)_(.*)") %>%
  mutate(
    # recode the event name for readability
    event = case_match(event,
                       "0" ~ "Baseline",
                       "12" ~ "Year 1",
                       "24" ~ "Year 2",
                       "36" ~ "Year 3"),
    
    # collapse the four transgender dummy variables into one
    kbi_y_trans_id = case_when(trans_no == 1 ~ "No",
                               trans_maybe == 1 ~ "Maybe",
                               trans_yes == 1 ~ "Yes",
                               trans_und == 1 ~ "I do not understand this question"),
    
    # recode the class variable to be more descriptive
    class_id_4 = case_match(class_id_4,
                            1 ~ "Class 4: Transgender",
                            2 ~ "Class 2: Naive",
                            3 ~ "Class 3: Questioning",
                            4 ~ "Class 1: Cisgender")) %>%
  select(-c(trans_no, trans_maybe, trans_yes, trans_und))

# read in the model means and standard errors for the continuous variables
means4 = read.csv(paste0(path, "mplus_gender_lca_means_4.csv"))

# format the means / standard errors datasets for plotting
means4 = means4 %>%
  mutate(event = gsub("\\D", "", measure),
         event = paste0("Year ", event),
         measure = substr(measure, 1, nchar(measure) - 1),
         measure = case_match(measure,
                              "FELTO" ~ "Sex Incongruent Felt Gender",
                              "FELTS" ~ "Sex Congruent Felt Gender",
                              "EXPRS" ~ "Gender Expression",
                              "WISH"  ~ "Gender Non-Contentedness"),
         measure = factor(measure, levels = c("Sex Incongruent Felt Gender", "Sex Congruent Felt Gender", "Gender Expression", "Gender Non-Contentedness"), ordered = TRUE),
         class_id = case_match(class_id,
                               1 ~ "4: Transgender",
                               2 ~ "2: Naive",
                               3 ~ "3: Questioning",
                               4 ~ "1: Cisgender"))

# barplot of responses to "are you transgender?" over time, by class
p1 = mplus_gender_lca %>%
  count(class_id_4, event, kbi_y_trans_id) %>%
  filter(!is.na(kbi_y_trans_id)) %>%
  group_by(class_id_4, event) %>%
  mutate(pct = n / sum(n) * 100) %>%
  ggplot(aes(x = event, y = pct, fill = kbi_y_trans_id)) +
  geom_bar(position = "stack", stat = "identity") +
  facet_wrap(~class_id_4, ncol = 2) +
  scale_fill_manual(values = c("#999999", "#CC79A7", "#0072B2", "#F0E442")) + 
  labs(fill = "Are you transgender?  ",
       y = "Percentage of Respondents") +
  guides(fill = guide_legend(nrow = 2, byrow = TRUE))

# lineplot of average gender conformity scores over time, by class
p2 = means4 %>%
  ggplot(aes(x = event, y = estimate, color = class_id, shape = class_id, group = class_id)) +
  geom_point(size = 3, alpha = 1) +
  geom_errorbar(aes(x = event, ymin = estimate - qnorm(.975)*se, ymax = estimate + qnorm(.975)*se), width = 0.2, linewidth = 1) +
  geom_line(linewidth = 1, alpha = 1) +
  facet_wrap(~measure, ncol = 2) +
  scale_x_discrete(expand = c(0, 0.35)) +
  scale_color_manual(values = c("#E69F00", "#56B4E9", "#D55E00", "#009E73")) + 
  scale_shape_manual(values = c(4, 15, 19, 17)) +
  labs(color = "Latent Class  ",
       shape = "Latent Class  ",
       y = "Score (with 95% Confidence Interval)") +
  theme(legend.key.width = unit(1, "cm")) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE))

p1; cat("<br><br><br>")

p2

ggsave(paste0(path, "abcd_gender_fig1.tiff"), plot = p1, width = 8, height = 8, dpi = 600)
ggsave(paste0(path, "abcd_gender_fig2.tiff"), plot = p2, width = 8, height = 8, dpi = 600)
```